language: node_js
node_js:
  - 14
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TRAVIS_GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  directories:
    - $HOME/.npm
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install codecov -g
  - npm ci --ignore-scripts
script:
  # run build script specified in package.json
  - npm i webdriver-manager
  - npm run ci
  # call script for deploying of produced artifacts
  - bash ./.travis-deploy.sh
after_success:
  - codecov
